### ISSUE TITLE
"System Tray" operation

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Minder-Desktop#2]
I think for an application like this to be used in the way we would like, it should have a system tray icon to which it minimizes, so on windows it doesn't clutter the taskbar:

https://github.com/nwjs/nw.js/wiki/tray

**Comment by jlucidar** [comment]
commit 7b6b233 tries to implement this feature.
So this is what have been implemented :
- if you minimize the application, it delete the icon  in the taskbar and open a tray icon.
- if you close (X) the application, it delete the icon  in the taskbar and open a tray icon.
- if you left click on the tray icon, it show the window
- if you right click on the tray icon, it open a menu, with a close button, that actually close totally the application.

I close the issue for now, let me know if this was not the expected behavior.
